# Generated by Django 5.2.14 on 2026-06-02 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='noticias_gustadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
