# Generated by Django 5.2.14 on 2026-06-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
